## MAKEFILE FOR C PROJECT

## PARAMETERS
INC_DIR := include
LIB_DIR :=
SRC_DIR := src
BIN_DIR := bin

EXE_NAME := sae1.02

EXE := $(BIN_DIR)/$(EXE_NAME)
SRC := $(wildcard $(SRC_DIR)/*.c)
OBJ := $(patsubst $(SRC_DIR)/%.c, $(BIN_DIR)/%.o, $(SRC))

#CC      := gcc
CFLAGS  := -I${INC_DIR} -MMD -MP -Wall
LDFLAGS := -lncurses
LDLIB   :=

#RM := rm
#TEMPLATES_FILES := ../templates/temp_files
##


.PHONY: build clean doc clflags init

build: $(EXE) | $(EXE_NAME)


## COMPILING
$(EXE): $(OBJ) | $(BIN_DIR)
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@

$(BIN_DIR)/%.o: $(SRC_DIR)/%.c | $(BIN_DIR)
	$(CC) $(CFLAGS) -c $< -o $@
##


## NEEDED
$(BIN_DIR):
	mkdir -p $@

$(EXE_NAME):
	ln -s $(EXE) .
##

-include $(OBJ:.o=.d)


## UTILS
clean:
	@$(RM) -rv $(BIN_DIR) $(EXE_NAME)

doc:
	@doxygen
	@echo "${PWD}/html/index.html"

clflags: compile_flags.txt

compile_flags.txt:
	echo -e "-I\n$(INC_DIR)" > $@

init:
	mkdir $(INC_DIR) $(SRC_DIR)
##

